/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra.user;

import hr.algebra.model.Article;
import hr.algebra.utils.IconUtils;
import hr.algebra.utils.MessageUtils;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author C
 */
public class ReadArticle extends javax.swing.JFrame {

    private final String NO_IMAGE_PATH = "assets" + File.separator + "no_image.png";
    /**
     * Creates new form ReadArticle for reading the content
     * @param article
     */
    public ReadArticle(Article article) {
        initComponents();
        init(article);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblLink = new javax.swing.JLabel();
        lblCreator = new javax.swing.JLabel();
        lblPubDate = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTitle = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtContent = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(872, 640));
        setMinimumSize(new java.awt.Dimension(872, 640));
        setSize(new java.awt.Dimension(872, 640));
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblImg.setMinimumSize(new java.awt.Dimension(340, 200));
        lblImg.setPreferredSize(new java.awt.Dimension(340, 200));

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel1.setText("Creator");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel2.setText("Published date");

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        jLabel3.setText("Category");

        lblLink.setFont(new java.awt.Font("sansserif", 0, 13)); // NOI18N
        lblLink.setText("Link");

        lblCreator.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblCreator.setText("Pero perio");

        lblPubDate.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblPubDate.setText("12.2.1212. 212.");

        lblCategory.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lblCategory.setText("Hrvatska");

        txtTitle.setEditable(false);
        txtTitle.setBackground(new java.awt.Color(214, 216, 223));
        txtTitle.setColumns(1);
        txtTitle.setFont(new java.awt.Font("sansserif", 1, 30)); // NOI18N
        txtTitle.setLineWrap(true);
        txtTitle.setRows(2);
        txtTitle.setText("Neki naslov nekog članka");
        txtTitle.setWrapStyleWord(true);
        txtTitle.setBorder(null);
        txtTitle.setFocusable(false);
        txtTitle.setOpaque(true);
        jScrollPane1.setViewportView(txtTitle);

        txtContent.setEditable(false);
        txtContent.setMaximumSize(new java.awt.Dimension(12, 24));
        txtContent.setName(""); // NOI18N
        jScrollPane2.setViewportView(txtContent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(lblCreator)
                            .addComponent(lblPubDate)
                            .addComponent(lblCategory)
                            .addComponent(lblLink)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPubDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLink))
                    .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    
    private void init(Article article) {
        txtTitle.setText(article.getTitle());
        lblCategory.setText(article.getCategory());
        lblCreator.setText(article.getCreator());
        lblPubDate.setText(article.getPublishedDate().format(Article.DATE_FORMATTER));
        
        buildHyperLink(article.getLink());
        
        if (article.getContent().equals("Err")) {
            txtContent.setText("There has been an error parsing the article. Please open the link in your browser!");
        } else {
            txtContent.setText(article.getContent());
        }
        
        try {
            lblImg.setIcon(IconUtils.createIcon(article.getPicturePath(), 340, 200));
        } catch (IOException iOException) {
            try {
                lblImg.setIcon(IconUtils.createIcon(NO_IMAGE_PATH, 340, 200));
            } catch (IOException iOException1) {
                lblImg.setText("NO IMAGE");
            }            
        }
    }

    private void buildHyperLink(String link) {
        lblLink.setForeground(Color.BLUE.darker());
        lblLink.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblLink.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(MouseEvent e) {
                try {         
                    Desktop.getDesktop().browse(new URI(link));
                } catch (IOException | URISyntaxException e1) {
                    MessageUtils.showErrorMessage("Error", "Cannot open link.");
                }
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                setCursor(Cursor.HAND_CURSOR);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                setCursor(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblLink;
    private javax.swing.JLabel lblPubDate;
    private javax.swing.JTextPane txtContent;
    private javax.swing.JTextArea txtTitle;
    // End of variables declaration//GEN-END:variables
}
