/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra.user;

import hr.algebra.dal.Repo;
import hr.algebra.dal.RepoFactory;
import hr.algebra.model.xml.Articles;
import hr.algebra.model.xml.Categories;
import hr.algebra.model.xml.Creators;
import hr.algebra.utils.FileUtils;
import hr.algebra.utils.MessageUtils;
import java.io.File;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;


/**
 *
 * @author C
 */
public class XmlDownloadPanel extends javax.swing.JPanel {

    private JAXBContext jaxbContext;
    private Articles articles;  
    private Categories categories;
    private Creators creators;
    private Repo repo;
    /**
     * Creates new form XmlDownload
     */
    public XmlDownloadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCreators = new javax.swing.JButton();
        btnCategories = new javax.swing.JButton();
        btnArticles = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Choose option:");

        btnCreators.setText("Creators");
        btnCreators.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatorsActionPerformed(evt);
            }
        });

        btnCategories.setText("Categories");
        btnCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriesActionPerformed(evt);
            }
        });

        btnArticles.setText("Articles");
        btnArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticlesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreators, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnCategories, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCreators, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnArticles, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCategories, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriesActionPerformed
        try {
            loadCategories();            
            File file = FileUtils.saveFile("XML files", "xml");
            if (file != null) {
                file = FileUtils.setFileExtension(file, "xml");
                marshalData(categories, file);
                MessageUtils.showInformationMessage("Success", "File created at:\n" + file.getAbsolutePath());
            }
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", "Cannot create XML file!");
        }
    }//GEN-LAST:event_btnCategoriesActionPerformed

    private void btnCreatorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatorsActionPerformed
        try {
            loadCreators();            
            File file = FileUtils.saveFile("XML files", "xml");
            if (file != null) {
                file = FileUtils.setFileExtension(file, "xml");
                marshalData(creators, file);
                MessageUtils.showInformationMessage("Success", "File created at:\n" + file.getAbsolutePath());
            }
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", "Cannot create XML file!");
        }
    }//GEN-LAST:event_btnCreatorsActionPerformed

    private void btnArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticlesActionPerformed
        try {
            loadArticles();            
            File file = FileUtils.saveFile("XML files", "xml");
            if (file != null) {
                file = FileUtils.setFileExtension(file, "xml");
                marshalData(articles, file);
                MessageUtils.showInformationMessage("Success", "File created at:\n" + file.getAbsolutePath());
            }
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", "Cannot create XML file!");
        }        
    }//GEN-LAST:event_btnArticlesActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticles;
    private javax.swing.JButton btnCategories;
    private javax.swing.JButton btnCreators;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void init() {
        try {
            initRepo();
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", "Cannot initiate form.");
        }
    }

    private void initRepo() throws Exception {
        repo = RepoFactory.getRepo();
    }

    private void loadArticles() throws Exception {
        articles = new Articles();
        articles.setArticles(repo.selectArticles());
    }

    private void loadCategories() throws Exception {
        categories = new Categories();
        categories.setCategories(repo.getCategories());
    }

    private void loadCreators() throws Exception {
        creators = new Creators();
        creators.setCreators(repo.getCreators());
    }
    
    private void marshalData(Object o, File f) throws JAXBException {
        jaxbContext = JAXBContext.newInstance(o.getClass());
        Marshaller jaxbMarshaller = jaxbContext.createMarshaller();    
        jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);        
        jaxbMarshaller.marshal(o, f);
    }
}
